<h1>Edit Question</h1>

<?php echo $this->tag->form("question/update/$question->question_id"); ?>

    <div class="form-group">
        <label for="email">Title</label>
        <?php
        echo $this->tag->textField([
            "question_title", 
            'class' => 'form-control', 
            'value' => $question->question_title
        ]); ?>
    </div>

    <div class="form-group">
        <label for="password">Question</label>
        <?php echo $this->tag->textField([
            "question_content", 
            'class' => 'form-control',
            'value' => $question->question_content
        ]); ?>
    </div>

    <div>
        <?php echo $this->tag->submitButton(["Edit", 'class' => 'my-3 btn btn-primary']); ?>
    </div>
</form>