<h2>Log In</h2>

<?php echo $this->tag->form("login/status"); ?>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField(["email", 'class' => 'form-control']); ?>
    </div>

    <div>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField(["password", 'class' => 'form-control']); ?>
    </div>

    <div>
        <?php echo $this->tag->submitButton(["Login", 'class' => 'my-3 btn btn-primary']); ?>
    </div>
</form>
