<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <div class="form-group">
        <label for="name">Name</label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control']); ?>
    </div>

    <div class="form-group">
        <label for="email">E-Mail</label>
        <?php echo $this->tag->emailField(["email", 'class' => 'form-control']); ?>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField(["password", 'class' => 'form-control']); ?>
    </div>

    <div class="form-group">
        <label for="conf_password">Confirm Password</label>
        <?php echo $this->tag->passwordField(["conf_password", 'class' => 'form-control']); ?>
    </div>

    <div>
        <?php echo $this->tag->submitButton(["Register", 'class' => 'my-3 btn btn-primary']); ?>
    </div>

</form>