<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP Framework</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark justify-content-between mb-4">
            <div class="px-4">
                <a href="/" class="navbar-brand mx-3">AskMe</a>
                <?php 
                    if($this->session->exists()) {
                        echo "<a href='/question/create' class=" . 'mx-3 nav-item-active nav-link' . ">Ask a Question</a>";
                    } ?>
            </div>

            <!-- Gabungkan dengan QuestionController -->
            <form class="form-inline" action="/search">
                <input class="form-control mr-sm-2" type="text" name="search">
                <button class="btn btn-success" type="submit">Search</button>
            </form>

            <div class="px-4">
                <?php 
                    if($this->session->has('auth')) {
                        // dont forget to implement profile on UserController
                        echo "<a href='/profile/" . $this->session->get('auth')['id'] . "'class=" . 'mx-3 nav-item text-muted' . ">" . 
                        $this->session->get('auth')['name'] . "</a>";
                        echo "<a href='/logout' class=" . 'mx-3 nav-item-active nav-link' . ">Logout</a>";
                    } 
                    else {    
                        echo "<a href='/login' class=" . 'mx-3 nav-item-active nav-link' . ">Log In</a>";
                        echo "<a href='/signup' class=" . 'mx-3 nav-item-active nav-link' . ">Sign Up</a>";
                    }
                    ?>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
